stages:
  - test

tests:
  stage: test
  # image: mcr.microsoft.com/playwright:v1.42.1-jammy
  image: node:18-alpine
  script:
    - npm i
    - npx playwright install --with-deps
    - node src/index.js
  variables:
    CI: "true"
